console.log('LINK: START')
let question = document.querySelector('.question')
let answerA = document.querySelector('.AnswerA')
let answerB = document.querySelector('.AnswerB')
let answerC = document.querySelector('.AnswerC')
let startButton = document.querySelector('#start')
console.log(question)
console.log(answerA)
console.log(answerB)
console.log(answerC)
console.log(startButton)